Marks xfail xgboost test due to scikit lib issue
Skips because we're seeing:
 > AttributeError: 'super' object has no attribute '__sklearn_tags__'
due to new library version rolling out and xgboost not being updated yet.